### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by neodevit** [contra/instax#1]
I want build c# win app for make photo with webcam and print with Instax Share SP
need
1) know a number of photo remain
2) print jpg from pc

study this project help me ?

thanks

**Comment by yocontra** [comment]
No, I never got anywhere with this project. You can decompile the android instax app to get protocol code, they left the source in there IIRC.

**Comment by neodevit** [comment]
sin
I wanted to do a photo cabinet with arduino c # and instant printer and facebook
i try to call with BT
